namespace SEToolbox.Interop
{
    public enum CubeType : byte
    {
        None,
        Exterior,
        Interior,
        Cube,
        SlopeCenterFrontTop,
        SlopeLeftFrontCenter,
        SlopeRightFrontCenter,
        SlopeCenterFrontBottom,
        SlopeLeftCenterTop,
        SlopeRightCenterTop,
        SlopeLeftCenterBottom,
        SlopeRightCenterBottom,
        SlopeCenterBackTop,
        SlopeLeftBackCenter,
        SlopeRightBackCenter,
        SlopeCenterBackBottom,
        NormalCornerLeftFrontTop,
        NormalCornerRightFrontTop,
        NormalCornerLeftBackTop,
        NormalCornerRightBackTop,
        NormalCornerLeftFrontBottom,
        NormalCornerRightFrontBottom,
        NormalCornerLeftBackBottom,
        NormalCornerRightBackBottom,
        InverseCornerLeftFrontTop,
        InverseCornerRightFrontTop,
        InverseCornerLeftBackTop,
        InverseCornerRightBackTop,
        InverseCornerLeftFrontBottom,
        InverseCornerRightFrontBottom,
        InverseCornerLeftBackBottom,
        InverseCornerRightBackBottom,

        // CornerSquare,
        // CornerSquareInverted,
        // HalfCorner,
        // HalfSlopeCorner,
        // HalfSlopeCornerInverted,
        // HalfSlopedCorner,
        // HalfSlopedCornerBase,
        // HalfSlopeInverted,
        // SlopedCorner,
        // SlopedCornerBase,
        // SlopedCornerTip,
        // RaisedSlopedCorner,
        // SlopeTransition,
        // SlopeTransitionBase,
        // SlopeTransitionBaseMirrored,
        // SlopeTransitionMirrored,
        // SlopeTransitionTip,
        // SlopeTransitionTipMirrored,
        // SquareSlopedCornerBase,
        // SquareSlopedCornerTip,
        // SquareSlopedCornerTipInv,

    };
}
