using System.ComponentModel;
using System.Diagnostics.Contracts;
using System.Globalization;
using System.Windows;
using System.Windows.Input;
using SEToolbox.Interfaces;
using SEToolbox.Models;
using SEToolbox.Services;
using SEToolbox.Views;

namespace SEToolbox.ViewModels
{
    public class StructurePlanetViewModel : StructureBaseViewModel<StructurePlanetModel>
    {
        private readonly IDialogService _dialogService;

        #region Ctor

        public StructurePlanetViewModel(BaseViewModel parentViewModel, StructurePlanetModel dataModel)
           : this(parentViewModel, dataModel, ServiceLocator.Resolve<IDialogService>())
        {
        }

        public StructurePlanetViewModel(BaseViewModel parentViewModel, StructurePlanetModel dataModel, IDialogService dialogService)
            : base(parentViewModel, dataModel)
        {
            Contract.Requires(dialogService != null);

            _dialogService = dialogService;

            DataModel.PropertyChanged += delegate (object sender, PropertyChangedEventArgs e)
            {
                // Will bubble property change events from the Model to the ViewModel.
                OnPropertyChanged(e.PropertyName);
            };
        }

        #endregion

        #region Command Properties

        public ICommand CopyDetailCommand => new DelegateCommand(CopyDetailExecuted, CopyDetailCanExecute);

        public ICommand RegenerateCommand => new DelegateCommand(RegenerateExecuted, RegenerateCanExecute);

        public ICommand CopyCenterGpsCommand => new DelegateCommand(CopyCenterGpsExecuted, CopyCenterGpsCanExecute);

        #endregion

        #region Properties

        protected new StructurePlanetModel DataModel
        {
           get => base.DataModel as StructurePlanetModel;
        }

        public string Name
        {
            get => DataModel.Name;
            set => DataModel.Name = value;
        }

        public BindableVector3DModel Center
        {
            get => new(DataModel.Center);
            set => DataModel.Center = value.ToVector3();
        }

        public float Radius
        {
            get => DataModel.Radius;
            set => DataModel.Radius = value;
        }

        public bool HasAtmosphere
        {
            get => DataModel.HasAtmosphere;
            set => DataModel.HasAtmosphere = value;
        }

        public float AtmosphereRadius
        {
            get => DataModel.AtmosphereRadius;
            set => DataModel.AtmosphereRadius = value;
        }

        public float MinimumSurfaceRadius
        {
            get => DataModel.MinimumSurfaceRadius;
            set => DataModel.MinimumSurfaceRadius = value;
        }

        public float MaximumHillRadius
        {
            get => DataModel.MaximumHillRadius;
            set => DataModel.MaximumHillRadius = value;
        }

        public float GravityFalloff
        {
            get => DataModel.GravityFalloff;
            set => DataModel.GravityFalloff = value;
        }

        public float SurfaceGravity
        {
            get => DataModel.SurfaceGravity;
            set => DataModel.SurfaceGravity = value;
        }

        public bool SpawnsFlora
        {
            get => DataModel.SpawnsFlora;
            set => DataModel.SpawnsFlora = value;
        }

        public bool ShowGPS
        {
            get => DataModel.ShowGPS;
            set
            {
                DataModel.ShowGPS = value;
                MainViewModel.IsModified = true;
            }
        }

        public string PlanetGenerator
        {
            get => DataModel.PlanetGenerator;
            set => DataModel.PlanetGenerator = value;
        }

        #endregion

        #region Methods

        public static bool CopyDetailCanExecute()
        {
            return true;
        }

        public void CopyDetailExecuted()
        {
            string detail = string.Format(Properties.Resources.CtlPlanetDetail,
                Name,
                Center.X, Center.Y, Center.Z,
                PlayerDistance,
                PositionAndOrientation.Value.Position.X, PositionAndOrientation.Value.Position.Y, PositionAndOrientation.Value.Position.Z,
                Radius,
                HasAtmosphere,
                AtmosphereRadius,
                MinimumSurfaceRadius,
                MaximumHillRadius,
                GravityFalloff,
                SurfaceGravity,
                SpawnsFlora,
                ShowGPS,
                PlanetGenerator);

            try
            {
                Clipboard.Clear();
                Clipboard.SetText(detail);
            }
            catch
            {
                // Ignore exception which may be generated by a Remote desktop session where Clipboard access has not been granted.
            }
        }


        public bool RegenerateCanExecute()
        {
            return true;
        }

        public void RegenerateExecuted()
        {
            RegeneratePlanetModel model = new();
            RegeneratePlanetViewModel loadVm = new(this, model);
            model.Load(DataModel.Seed, DataModel.Radius);
            bool? result = _dialogService.ShowDialog<WindowRegeneratePlanet>(this, loadVm);
            if (result == true)
            {
                DataModel.RegeneratePlanet(model.Seed, (float)model.Diameter / 2f);
                MainViewModel.IsModified = true;
            }
        }

        public bool CopyCenterGpsCanExecute()
        {
            return !IsBusy;
        }

        public void CopyCenterGpsExecuted()
        {
            string text = string.Format(CultureInfo.InvariantCulture, $"GPS:{ DataModel.DisplayName.Replace(":", "_").Replace("&", "_")}:{DataModel.Center.X:0.00}:{ DataModel.Center.Y:0.00}:{DataModel.Center.Z:0.00}:");
            try
            {
                Clipboard.Clear();
                Clipboard.SetText(text);
            }
            catch
            {
                // Ignore exception which may be generated by a Remote desktop session where Clipboard access has not been granted.
            }
        }

        #endregion
    }
}
